services:
  web:
    build: .
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/usersmgmt
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: usersmgmt
    volumes:
      - api_db_data:/var/lib/postgresql/data

volumes:
  api_db_data: